-- SEQUENCES 생성
CREATE SEQUENCE MOVIE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ACTOR_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE REVIEW_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- MOVIE 테이블 생성
CREATE TABLE MOVIE (
    MOVIE_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(200),
    RELEASE_DATE DATE,
    GENRE VARCHAR2(100),
    DIRECTOR VARCHAR2(100)
);

-- ACTOR 테이블 생성
CREATE TABLE ACTOR (
    ACTOR_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    BIRTHDATE DATE,
    NATIONALITY VARCHAR2(50)
);

-- MOVIE_ACTOR 테이블 생성 (MOVIE, ACTOR 연결)
CREATE TABLE MOVIE_ACTOR (
    MOVIE_ID NUMBER REFERENCES MOVIE(MOVIE_ID),
    ACTOR_ID NUMBER REFERENCES ACTOR(ACTOR_ID),
    ROLE VARCHAR2(100),
    PRIMARY KEY (MOVIE_ID, ACTOR_ID)
);

-- REVIEW 테이블 생성 (USER_INFO, MOVIE 연결)
CREATE TABLE REVIEW (
    REVIEW_ID NUMBER PRIMARY KEY,
    MOVIE_ID NUMBER REFERENCES MOVIE(MOVIE_ID),
    USER_ID NUMBER REFERENCES USER_INFO(USER_ID),
    RATING NUMBER(2,1),
    "COMMENT" VARCHAR2(1000),
    REVIEW_DATE DATE
);

-- MOVIE 테이블에 데이터 삽입
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '명량', TO_DATE('2014-07-30', 'YYYY-MM-DD'), '전쟁, 드라마', '김한민');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '도둑들', TO_DATE('2012-07-25', 'YYYY-MM-DD'), '범죄, 액션', '최동훈');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '베테랑', TO_DATE('2015-08-05', 'YYYY-MM-DD'), '액션, 코미디', '류승완');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '광해, 왕이 된 남자', TO_DATE('2012-09-13', 'YYYY-MM-DD'), '사극, 드라마', '추창민');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '7번방의 선물', TO_DATE('2013-01-23', 'YYYY-MM-DD'), '드라마, 코미디', '이환경');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '암살', TO_DATE('2015-07-22', 'YYYY-MM-DD'), '액션, 드라마', '최동훈');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '국제시장', TO_DATE('2014-12-17', 'YYYY-MM-DD'), '드라마', '윤제균');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '해운대', TO_DATE('2009-07-22', 'YYYY-MM-DD'), '재난, 드라마', '윤제균');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '신과함께-죄와 벌', TO_DATE('2017-12-20', 'YYYY-MM-DD'), '판타지, 드라마', '김용화');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '부산행', TO_DATE('2016-07-20', 'YYYY-MM-DD'), '액션, 스릴러', '연상호');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '터널', TO_DATE('2016-08-10', 'YYYY-MM-DD'), '드라마, 스릴러', '김성훈');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '곡성', TO_DATE('2016-05-12', 'YYYY-MM-DD'), '미스터리, 스릴러', '나홍진');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '택시운전사', TO_DATE('2017-08-02', 'YYYY-MM-DD'), '드라마', '장훈');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '1987', TO_DATE('2017-12-27', 'YYYY-MM-DD'), '드라마', '장준환');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '신과함께-인과 연', TO_DATE('2018-08-01', 'YYYY-MM-DD'), '판타지, 드라마', '김용화');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '공조', TO_DATE('2017-01-18', 'YYYY-MM-DD'), '액션, 코미디', '김성훈');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '범죄도시', TO_DATE('2017-10-03', 'YYYY-MM-DD'), '액션, 범죄', '강윤성');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '검사외전', TO_DATE('2016-02-03', 'YYYY-MM-DD'), '범죄, 코미디', '이일형');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '내부자들', TO_DATE('2015-11-19', 'YYYY-MM-DD'), '범죄, 드라마', '우민호');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '더 킹', TO_DATE('2017-01-18', 'YYYY-MM-DD'), '범죄, 드라마', '한재림');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '마스터', TO_DATE('2016-12-21', 'YYYY-MM-DD'), '범죄, 액션', '조의석');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '밀정', TO_DATE('2016-09-07', 'YYYY-MM-DD'), '스릴러', '김지운');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '공작', TO_DATE('2018-08-08', 'YYYY-MM-DD'), '스릴러', '윤종빈');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '마약왕', TO_DATE('2018-12-19', 'YYYY-MM-DD'), '범죄, 드라마', '우민호');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '암수살인', TO_DATE('2018-10-03', 'YYYY-MM-DD'), '스릴러', '김태균');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '극한직업', TO_DATE('2019-01-23', 'YYYY-MM-DD'), '코미디, 액션', '이병헌');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '기생충', TO_DATE('2019-05-30', 'YYYY-MM-DD'), '드라마', '봉준호');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '백두산', TO_DATE('2019-12-19', 'YYYY-MM-DD'), '액션, 드라마', '이병헌');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '남산의 부장들', TO_DATE('2020-01-22', 'YYYY-MM-DD'), '드라마', '우민호');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '다만 악에서 구하소서', TO_DATE('2020-08-05', 'YYYY-MM-DD'), '액션, 스릴러', '홍원찬');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '서복', TO_DATE('2021-04-15', 'YYYY-MM-DD'), 'SF, 드라마', '이용주');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '모가디슈', TO_DATE('2021-07-28', 'YYYY-MM-DD'), '액션, 드라마', '류승완');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '싱크홀', TO_DATE('2021-08-11', 'YYYY-MM-DD'), '재난, 코미디', '김지훈');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '파묘', TO_DATE('2024-02-22', 'YYYY-MM-DD'), '미스터리, 스릴러', '장재현');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '외계+인 2부', TO_DATE('2024-01-10', 'YYYY-MM-DD'), '액션, 드라마, 판타지', '최동훈');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '시민덕희', TO_DATE('2024-01-24', 'YYYY-MM-DD'), '드라마', '박영주');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '도그 데이즈', TO_DATE('2024-02-07', 'YYYY-MM-DD'), '드라마', '김덕민');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '히트맨 2', TO_DATE('2025-01-22', 'YYYY-MM-DD'), '코미디', '최원섭');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '검은 수녀들', TO_DATE('2025-01-24', 'YYYY-MM-DD'), '미스터리', '권혁재');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '말할 수 없는 비밀', TO_DATE('2025-01-28', 'YYYY-MM-DD'), '판타지', '서유민');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '브로큰', TO_DATE('2025-02-05', 'YYYY-MM-DD'), '범죄', '김진황');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '스트리밍', TO_DATE('2025-03-21', 'YYYY-MM-DD'), '스릴러', '조창호');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '로비', TO_DATE('2025-04-02', 'YYYY-MM-DD'), '드라마', '하정우');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '마루이 비디오', TO_DATE('2024-04-24', 'YYYY-MM-DD'), '스릴러', '김진환');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '탈출: PROJECT SILENCE', TO_DATE('2024-07-10', 'YYYY-MM-DD'), '스릴러', '김태곤');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '비상선언', TO_DATE('2024-08-21', 'YYYY-MM-DD'), '재난, 드라마', '한재림');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '하이재킹', TO_DATE('2024-05-15', 'YYYY-MM-DD'), '액션, 스릴러', '김성훈');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '노량: 죽음의 바다', TO_DATE('2024-12-20', 'YYYY-MM-DD'), '역사, 전쟁', '김한민');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '귀공자', TO_DATE('2024-06-26', 'YYYY-MM-DD'), '액션, 스릴러', '박훈정');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '보호자', TO_DATE('2024-11-27', 'YYYY-MM-DD'), '드라마, 액션', '정우성');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '밀수', TO_DATE('2024-09-18', 'YYYY-MM-DD'), '범죄, 드라마', '류승완');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '정직한 후보 3', TO_DATE('2024-10-30', 'YYYY-MM-DD'), '코미디', '장유정');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '청춘', TO_DATE('2024-11-13', 'YYYY-MM-DD'), '드라마', '박찬욱');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '헤어질 결심', TO_DATE('2024-10-05', 'YYYY-MM-DD'), '로맨스, 스릴러', '박찬욱');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '드림', TO_DATE('2024-06-01', 'YYYY-MM-DD'), '드라마', '이병헌');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '헌트', TO_DATE('2024-08-03', 'YYYY-MM-DD'), '스릴러', '이정재');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '콘크리트 유토피아', TO_DATE('2024-12-25', 'YYYY-MM-DD'), '드라마, 스릴러', '엄태화');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '소울메이트', TO_DATE('2024-07-22', 'YYYY-MM-DD'), '드라마', '민용근');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '영웅', TO_DATE('2024-10-14', 'YYYY-MM-DD'), '뮤지컬, 드라마', '윤제균');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '경관의 피', TO_DATE('2024-12-13', 'YYYY-MM-DD'), '범죄, 스릴러', '이규만');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '유체이탈자', TO_DATE('2024-10-07', 'YYYY-MM-DD'), '액션, 스릴러', '윤재근');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '담보', TO_DATE('2024-12-29', 'YYYY-MM-DD'), '드라마', '강대규');
INSERT INTO MOVIE (MOVIE_ID, TITLE, RELEASE_DATE, GENRE, DIRECTOR)
VALUES (MOVIE_SEQ.NEXTVAL, '소리도 없이', TO_DATE('2024-08-15', 'YYYY-MM-DD'), '드라마', '홍의정');

-- ACTOR 테이블에 삽입
-- 배우 정보 삽입
INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '최민식', TO_DATE('1962-04-27', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '김윤석', TO_DATE('1968-01-21', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '하정우', TO_DATE('1978-03-11', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '황정민', TO_DATE('1970-09-01', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '류승룡', TO_DATE('1970-11-29', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '송강호', TO_DATE('1967-01-17', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '이병헌', TO_DATE('1970-07-12', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '조진웅', TO_DATE('1976-03-03', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '유해진', TO_DATE('1970-01-04', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '마동석', TO_DATE('1971-03-01', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '정우성', TO_DATE('1973-03-20', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '이정재', TO_DATE('1972-12-15', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '김혜수', TO_DATE('1970-09-05', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '전지현', TO_DATE('1981-10-30', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '조정석', TO_DATE('1980-12-26', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '김태리', TO_DATE('1990-04-24', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '박보검', TO_DATE('1993-06-16', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '김수현', TO_DATE('1988-02-16', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '수지', TO_DATE('1994-10-10', 'YYYY-MM-DD'), '대한민국');

INSERT INTO ACTOR (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY)
VALUES (ACTOR_SEQ.NEXTVAL, '이정은', TO_DATE('1970-01-06', 'YYYY-MM-DD'), '대한민국');

INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (1, 1, '이순신');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (2, 14, '예니콜');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (2, 12, '뽀빠이');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (3, 4, '서도철');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (3, 9, '조태오');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (4, 6, '광해');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (5, 5, '용구');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (5, 10, '양호');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (6, 14, '안옥윤');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (6, 2, '염석진');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (7, 4, '덕수');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (8, 9, '만식');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (9, 3, '강림');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (9, 5, '해원맥');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (10, 6, '석우');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (11, 4, '정수');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (12, 6, '종구');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (13, 6, '김만섭');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (14, 2, '박처장');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (15, 3, '강림');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (15, 5, '해원맥');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (16, 7, '림철령');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (16, 9, '강진태');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (17, 10, '마석도');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (18, 7, '변재욱');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (19, 7, '안상구');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (20, 7, '박태수');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (21, 7, '김재명');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (22, 2, '이정출');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (23, 7, '박석영');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (24, 6, '이두삼');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (25, 2, '김형민');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (26, 5, '고반장');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (27, 6, '기택');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (28, 7, '조인창');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (29, 2, '김규평');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (30, 7, '인남');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (31, 7, '기헌');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (32, 4, '한신성');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (33, 9, '동원');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (34, 6, '상훈');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (35, 14, '이안');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (36, 13, '덕희');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (37, 3, '주인공');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (38, 3, '준');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (39, 16, '수녀');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (40, 17, '주인공');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (41, 18, '형사');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (42, 19, '주인공');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (43, 3, '로비스트');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (44, 20, '주인공');
INSERT INTO MOVIE_ACTOR (MOVIE_ID, ACTOR_ID, ROLE) VALUES (45, 3, '주인공');

COMMIT;

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
SELECT * FROM REVIEW;
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE)
VALUES (REVIEW_SEQ.NEXTVAL, 1, 3, 4.5, '긴장감 넘치는 전투 장면!', TO_DATE('2024-05-25', 'YYYY-MM-DD'));

INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE)
VALUES (REVIEW_SEQ.NEXTVAL, 5, 8, 3.0, '감동적이지만 조금 지루했음.', TO_DATE('2024-05-28', 'YYYY-MM-DD'));

INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE)
VALUES (REVIEW_SEQ.NEXTVAL, 10, 1, 4.8, '좀비 액션이 최고였어요!', TO_DATE('2024-06-01', 'YYYY-MM-DD'));

INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE)
VALUES (REVIEW_SEQ.NEXTVAL, 15, 7, 2.5, '스토리가 아쉬웠음.', TO_DATE('2024-05-30', 'YYYY-MM-DD'));

INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE)
VALUES (REVIEW_SEQ.NEXTVAL, 21, 5, 4.2, '배우들 연기력이 대단!', TO_DATE('2024-05-29', 'YYYY-MM-DD'));

INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE)
VALUES (REVIEW_SEQ.NEXTVAL, 27, 11, 5.0, '명작 그 자체, 몰입감 최고!', TO_DATE('2024-06-02', 'YYYY-MM-DD'));

INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE)
VALUES (REVIEW_SEQ.NEXTVAL, 30, 4, 3.7, '액션은 멋졌지만 스토리가 약해요.', TO_DATE('2024-06-01', 'YYYY-MM-DD'));

INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE)
VALUES (REVIEW_SEQ.NEXTVAL, 33, 10, 4.0, '코믹 요소가 잘 살아있음.', TO_DATE('2024-05-27', 'YYYY-MM-DD'));

INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE)
VALUES (REVIEW_SEQ.NEXTVAL, 39, 14, 2.0, '스토리가 너무 평범해요.', TO_DATE('2024-05-26', 'YYYY-MM-DD'));

INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE)
VALUES (REVIEW_SEQ.NEXTVAL, 42, 9, 4.5, '긴박한 전개가 좋았어요.', TO_DATE('2024-06-01', 'YYYY-MM-DD'));

INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 33, 23, 3.1, '생각보다 평범했어요.', TO_DATE('2024-05-25', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 28, 6, 2.0, '화려한 액션!', TO_DATE('2024-05-31', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 40, 3, 3.5, '생각보다 평범했어요.', TO_DATE('2024-05-26', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 37, 23, 2.3, '감동적이었어요.', TO_DATE('2024-05-25', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 32, 7, 3.0, '스토리가 탄탄했음.', TO_DATE('2024-05-28', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 27, 16, 2.9, '긴박감 넘쳤습니다.', TO_DATE('2024-05-25', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 23, 8, 1.8, '생각보다 평범했어요.', TO_DATE('2024-06-01', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 35, 19, 1.0, '지루하진 않았어요.', TO_DATE('2024-05-26', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 18, 12, 3.7, '지루하진 않았어요.', TO_DATE('2024-06-01', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 39, 17, 4.8, '재밌게 봤어요!', TO_DATE('2024-05-29', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 4, 21, 1.2, '화려한 액션!', TO_DATE('2024-05-25', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 44, 14, 1.8, '긴박감 넘쳤습니다.', TO_DATE('2024-06-01', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 26, 21, 4.3, '시간 가는 줄 몰랐음.', TO_DATE('2024-05-26', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 29, 7, 2.7, '스토리 전개가 흥미로웠음.', TO_DATE('2024-05-29', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 14, 7, 3.4, '스토리가 탄탄했음.', TO_DATE('2024-06-01', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 18, 20, 3.7, '연기력이 좋았어요.', TO_DATE('2024-05-27', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 44, 10, 2.3, '화려한 액션!', TO_DATE('2024-05-25', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 43, 2, 4.3, '연기력이 좋았어요.', TO_DATE('2024-05-25', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 8, 12, 4.0, '시간 가는 줄 몰랐음.', TO_DATE('2024-05-25', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 50, 24, 1.2, '시간 가는 줄 몰랐음.', TO_DATE('2024-05-30', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 28, 14, 1.2, '긴박감 넘쳤습니다.', TO_DATE('2024-05-30', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 44, 3, 3.1, '지루하진 않았어요.', TO_DATE('2024-05-26', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 11, 4, 3.9, '재밌게 봤어요!', TO_DATE('2024-05-27', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 42, 2, 3.0, '스토리가 탄탄했음.', TO_DATE('2024-06-01', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 38, 8, 3.8, '생각보다 평범했어요.', TO_DATE('2024-05-30', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 40, 19, 3.3, '감동적이었어요.', TO_DATE('2024-05-25', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 31, 4, 3.3, '감동적이었어요.', TO_DATE('2024-05-31', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 43, 9, 2.9, '재밌게 봤어요!', TO_DATE('2024-06-01', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 37, 12, 4.2, '지루하진 않았어요.', TO_DATE('2024-05-26', 'YYYY-MM-DD'));
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, USER_ID, RATING, "COMMENT", REVIEW_DATE) VALUES (REVIEW_SEQ.NEXTVAL, 23, 20, 4.1, '감동적이었어요.', TO_DATE('2024-06-01', 'YYYY-MM-DD'));



COMMIT;