CREATE TABLE USER_INFO (
 USER_NO INT PRIMARY KEY AUTO_INCREMENT ,
 ID VARCHAR(50) UNIQUE NOT NULL,
 PASSWORD VARCHAR(300) NOT NULL,
 EMAIL VARCHAR(100) UNIQUE ,
 NAME VARCHAR(50) NOT NULL,
 PHONE VARCHAR(50) UNIQUE,
 ADDR VARCHAR(200),
 GENDER VARCHAR(10), CHECK(GENDER IN ('남', '여')),
 BIRTH_DATE DATE,
 HIRE_DATE DATE DEFAULT (CURRENT_DATE),
 QUIT_DATE DATE,
 DEPT_NO INT,
 GRADE_NO INT
);
CREATE TABLE DEPARTMENT(
   DEPT_NO INT PRIMARY KEY AUTO_INCREMENT,
   DEPT_NAME VARCHAR(100) NOT NULL /*개발팀*/
);
CREATE TABLE GRADE( 
   GRADE_NO INT PRIMARY KEY AUTO_INCREMENT,
   GRADE_NAME VARCHAR(100) NOT NULL  /*사원*/
);
/*DEPT_NO, GRADE_NO*/
ALTER TABLE USER_INFO ADD
FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENT (DEPT_NO);
ALTER TABLE USER_INFO ADD
FOREIGN KEY(GRADE_NO) REFERENCES GRADE_NO;

CREATE TABLE PROJECT (
   PRO_NO INT AUTO_INCREMENT PRIMARY KEY,
   PRO_NAME VARCHAR(100) NOT NULL,
   PRO_DESC TEXT,
   START_DATE DATE,
   END_DATE DATE,
   STATUS VARCHAR(10) CHECK(STATUS IN ( '진행전', '진행중', '완료', '중단'))
);
CREATE TABLE MEMBERS (
   MEMBER_NO INT AUTO_INCREMENT PRIMARY KEY,
   USER_NO INT,
   PRO_NO INT,
   ROLE VARCHAR(50)
);
/*프로젝트 : 업무들 = 1: M*/
CREATE TABLE PROJECT_TASKS (
   TASK_NO INT AUTO_INCREMENT PRIMARY KEY,
   PRO_NO INT,
   TASK_NAME VARCHAR(100),
   TASK_DESC TEXT,
   STATUS VARCHAR(30) CHECK (TASK_STATUS IN ('진행전', '진행중', '완료', '중단')),
   START_DATE DATE,
   END_DATE DATE
   );
-------------------------------------------
/*PROJECT_MEMBERS : USER_NO, POR_NO*/
ALTER TABLE PROJECT_MEMBERS ADD
FOREIGN KEY (USER_NO) REFERENCES USER_INFO(USER_NO);
ALTER TABLE PROJECT_MEMBERS ADD
FOREIGN KEY (PRO_NO) REFERENCES PROJECT(PRO_NO);
/*PROJECT_TASKS : PRP_NO*/
ALTER TABLE PROJECT_TASKS ADD
FOREIGN KEY (PRO_NO) REFERENCES PROJECT(PRO_NO);